SELECT COUNT(ANIMAL_ID) AS COUNT
FROM (SELECT * FROM ANIMAL_INS GROUP BY NAME) AS ANIMAL_INS
WHERE NAME IS NOT NULL


# SELECT COUNT(DISTINCT NAME) AS COUNT
# FROM ANIMAL_INS

# SELECT COUNT(ANIMAL_ID) AS 'COUNT' 
# FROM (SELECT * FROM ANIMAL_INS GROUP BY NAME) s
# WHERE NAME IS NOT NULL;