SELECT II.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO II LEFT JOIN ITEM_TREE IT 
    ON II.ITEM_ID = IT.PARENT_ITEM_ID
WHERE IT.PARENT_ITEM_ID IS NULL
ORDER BY II.ITEM_ID DESC

# SELECT ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO
# WHERE ITEM_ID NOT IN (SELECT DISTINCT PARENT_ITEM_ID
#                       FROM ITEM_TREE 
#                       WHERE PARENT_ITEM_ID IS NOT NULL)
# ORDER BY ITEM_ID DESC