SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP, REST_REVIEW RR
WHERE MP.MEMBER_ID = RR.MEMBER_ID
AND MP.MEMBER_ID = (
    SELECT MEMBER_ID FROM REST_REVIEW
    GROUP BY MEMBER_ID 
    ORDER BY COUNT(REVIEW_TEXT) DESC
    LIMIT 1
)

ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT