SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, (TEMP.SIZE_OF_COLONY-ED.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA ED JOIN 
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR) TEMP ON YEAR(ED.DIFFERENTIATION_DATE) = TEMP.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC



